---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: ed-app-trigger-binding
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.html_url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-repo-tag-name
    value: $(body.ref)
