---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ed-app-trigger-template
spec:
  params:
    - name: git-repo-url
      description: The git repository url
    - name: git-repo-name
      description: The name of the git repository
    - name: git-repo-tag-name
      description: The name of the git tag

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        namespace: ed-app
        generateName: ed-app-
        labels:
          tekton.dev/pipeline: build-and-deploy
      spec:
        params:
          - name: git-url
            value: $(tt.params.git-repo-url)
          - name: git-tag
            value: $(tt.params.git-repo-tag-name)
        pipelineRef:
          name: build-and-deploy
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              metadata:
                creationTimestamp: null
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: gp2
                volumeMode: Filesystem
              status: {}