---
# ansible-runner-task.yml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ansible-runner
spec:
  description: >-
    Task to run Ansible playbooks using Ansible Runner
  workspaces:
    - name: runner-dir
      description: The Ansible runner directory
  params:
    - name: project-dir
      description: The project directory under the workspace runner-dir
      default: 'ansible'
    - name: args
      description: The arguments to pass ansible-runner
      type: array
      default:
        - -p
        - deploy-app.yml
  steps:
    - name: run-playbook
      image: image-registry.openshift-image-registry.svc:5000/ed-app/ee-supported-rhel8
      command: ['ansible-runner']
      args:
        - run
        - $(params.args[*])
        - $(params.project-dir)
      workingDir: '$(workspaces.runner-dir.path)'
