---
# ansible-runner-pipeline.yml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ansible-job
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: ansible-project-dir
    - name: ansible-playbook-file
    - name: tower-secret
      default: 'toweraccess'
  workspaces:
    - name: git-source
  tasks:
    - name: fetch-from-git
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: git-source

    - name: set-ansible-vars
      runAfter:
        - fetch-from-git
      workspaces:
        - name: repo-dir
          workspace: git-source
      params:
        - name: project-dir
          value: $(params.ansible-project-dir)
      taskSpec:
        steps:
        - image: registry.access.redhat.com/ubi8/ubi-minimal
          name: set-vars
          script: |
            mkdir -p $(workspaces.repo-dir.path)/$(params.project-dir)/env/
            cat > $(workspaces.repo-dir.path)/$(params.project-dir)/env/extravars <<EOF
            ---
            ansible_controller_extra_vars: 
              application: httpd
            EOF
            pwd
            ls $(workspaces.repo-dir.path)/$(params.project-dir)/env/
            cat $(workspaces.repo-dir.path)/$(params.project-dir)/env/extravars
      
    - name: ansible-job
      runAfter:
        - set-ansible-vars
      taskRef:
        name: ansible-runner
      params:
        - name: project-dir
          value: $(params.ansible-project-dir)
        - name: tower-secret
          value: $(params.tower-secret)
        - name: args
          value: 
            - '-p'
            - $(params.ansible-playbook-file)
      workspaces:
        - name: runner-dir
          workspace: git-source
